# Generated by Django 4.1.2 on 2022-11-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_department_delete_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('middlename', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='department',
            old_name='Name',
            new_name='name',
        ),
    ]
