# Generated by Django 4.1.2 on 2022-11-03 10:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_employees_rename_name_department_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodGroup', models.IntegerField(validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(0)])),
                ('emergencyPhoneNumber', models.CharField(max_length=20)),
                ('registrationDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('middlename', models.CharField(blank=True, max_length=20)),
                ('dateOfBirth', models.DateField()),
                ('iin', models.CharField(max_length=20)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=20)),
                ('maritalStatus', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'In reserve'), ('R', 'Retired')], max_length=1)),
                ('type', models.CharField(choices=[('D', 'Doctor'), ('S', 'Staff')], max_length=1)),
                ('specializationId', models.CharField(max_length=30)),
                ('experience', models.IntegerField()),
                ('photo', models.ImageField(blank=True, upload_to='photos')),
                ('category', models.IntegerField()),
                ('price', models.IntegerField()),
                ('degree', models.CharField(max_length=30)),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('homepage', models.CharField(max_length=30)),
                ('departmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
