# Generated by Django 4.1.2 on 2022-11-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
